### ISSUE TITLE
React Ref support

### ISSUE THREAD

**Issue by BrOrlandi** [nckblu/react-image-and-background-image-fade#5]
It's possible to support the use of `ref` forwarding to the container element?

My use case:
I need to pass a Ref so I can get the container width before the image loads so I can maintain the aspect ratio by changing the height to width * 9/16.

Let me know if it's possible.

**Comment by nckblu** [comment]
This can be achieved using the isResponsive prop which effectively calculates the ratio for you. 
Ref support has been added in the latest version.
